-- MySQL Script generated by MySQL Workbench
-- Wed May  8 19:49:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `idcard` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `defense` INT NULL,
  `damage` INT NULL,
  `price` INT NULL,
  `description` VARCHAR(255) NULL,
  `img` VARCHAR(255) NULL,
  PRIMARY KEY (`idcard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`class` ;

CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `idclass` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`idclass`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deck` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deck` (
  `iddeck` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `class_idclass` INT NOT NULL,
  PRIMARY KEY (`iddeck`),
  INDEX `fk_deck_class1_idx` (`class_idclass` ASC),
  CONSTRAINT `fk_deck_class1`
    FOREIGN KEY (`class_idclass`)
    REFERENCES `mydb`.`class` (`idclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `idplayer` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `gold` INT NULL,
  `numwin` INT NULL,
  `numlose` INT NULL,
  PRIMARY KEY (`idplayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card_has_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`card_has_player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`card_has_player` (
  `card_idcard` INT NOT NULL,
  `player_idplayer` INT NOT NULL,
  PRIMARY KEY (`card_idcard`, `player_idplayer`),
  INDEX `fk_carta_has_player_player1_idx` (`player_idplayer` ASC),
  INDEX `fk_carta_has_player_carta_idx` (`card_idcard` ASC),
  CONSTRAINT `fk_carta_has_player_carta`
    FOREIGN KEY (`card_idcard`)
    REFERENCES `mydb`.`card` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carta_has_player_player1`
    FOREIGN KEY (`player_idplayer`)
    REFERENCES `mydb`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deck_has_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deck_has_card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deck_has_card` (
  `deck_iddeck` INT NOT NULL,
  `card_idcard` INT NOT NULL,
  PRIMARY KEY (`deck_iddeck`, `card_idcard`),
  INDEX `fk_deck_has_carta_carta1_idx` (`card_idcard` ASC),
  INDEX `fk_deck_has_carta_deck1_idx` (`deck_iddeck` ASC),
  CONSTRAINT `fk_deck_has_carta_deck1`
    FOREIGN KEY (`deck_iddeck`)
    REFERENCES `mydb`.`deck` (`iddeck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deck_has_carta_carta1`
    FOREIGN KEY (`card_idcard`)
    REFERENCES `mydb`.`card` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deck_has_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`deck_has_player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`deck_has_player` (
  `deck_iddeck` INT NOT NULL,
  `player_idplayer` INT NOT NULL,
  PRIMARY KEY (`deck_iddeck`, `player_idplayer`),
  INDEX `fk_deck_has_player_player1_idx` (`player_idplayer` ASC),
  INDEX `fk_deck_has_player_deck1_idx` (`deck_iddeck` ASC),
  CONSTRAINT `fk_deck_has_player_deck1`
    FOREIGN KEY (`deck_iddeck`)
    REFERENCES `mydb`.`deck` (`iddeck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deck_has_player_player1`
    FOREIGN KEY (`player_idplayer`)
    REFERENCES `mydb`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`battlelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`battlelog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`battlelog` (
  `idbattlelog` INT NOT NULL AUTO_INCREMENT,
  `result` INT NULL,
  `rankpoints` INT NULL,
  PRIMARY KEY (`idbattlelog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`battlelog_has_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`battlelog_has_player` ;

CREATE TABLE IF NOT EXISTS `mydb`.`battlelog_has_player` (
  `battlelog_idbattlelog` INT NOT NULL,
  `player_idplayer` INT NOT NULL,
  PRIMARY KEY (`battlelog_idbattlelog`, `player_idplayer`),
  INDEX `fk_battlelog_has_player_player1_idx` (`player_idplayer` ASC),
  INDEX `fk_battlelog_has_player_battlelog1_idx` (`battlelog_idbattlelog` ASC),
  CONSTRAINT `fk_battlelog_has_player_battlelog1`
    FOREIGN KEY (`battlelog_idbattlelog`)
    REFERENCES `mydb`.`battlelog` (`idbattlelog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_battlelog_has_player_player1`
    FOREIGN KEY (`player_idplayer`)
    REFERENCES `mydb`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`effect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`effect` ;

CREATE TABLE IF NOT EXISTS `mydb`.`effect` (
  `ideffect` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` INT NULL,
  PRIMARY KEY (`ideffect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`effect_has_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`effect_has_card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`effect_has_card` (
  `effect_ideffect` INT NOT NULL,
  `card_idcard` INT NOT NULL,
  PRIMARY KEY (`effect_ideffect`, `card_idcard`),
  INDEX `fk_effect_has_card_card1_idx` (`card_idcard` ASC),
  INDEX `fk_effect_has_card_effect1_idx` (`effect_ideffect` ASC),
  CONSTRAINT `fk_effect_has_card_effect1`
    FOREIGN KEY (`effect_ideffect`)
    REFERENCES `mydb`.`effect` (`ideffect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effect_has_card_card1`
    FOREIGN KEY (`card_idcard`)
    REFERENCES `mydb`.`card` (`idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_has_effect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`class_has_effect` ;

CREATE TABLE IF NOT EXISTS `mydb`.`class_has_effect` (
  `class_idclass` INT NOT NULL,
  `effect_ideffect` INT NOT NULL,
  PRIMARY KEY (`class_idclass`, `effect_ideffect`),
  INDEX `fk_class_has_effect_effect1_idx` (`effect_ideffect` ASC),
  INDEX `fk_class_has_effect_class1_idx` (`class_idclass` ASC),
  CONSTRAINT `fk_class_has_effect_class1`
    FOREIGN KEY (`class_idclass`)
    REFERENCES `mydb`.`class` (`idclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_has_effect_effect1`
    FOREIGN KEY (`effect_ideffect`)
    REFERENCES `mydb`.`effect` (`ideffect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
